"""baseline schema

Revision ID: 00bdf9aea347
Revises: 
Create Date: 2026-07-14 19:07:13.569977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00bdf9aea347'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ajustes_calibracion',
    sa.Column('rubrica_version_hash', sa.String(length=64), nullable=False),
    sa.Column('criterio', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('direccion', sa.String(length=10), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('recurrencia', sa.Integer(), nullable=False),
    sa.Column('confianza', sa.Float(), nullable=False),
    sa.Column('evidencia_json', sa.Text(), nullable=True),
    sa.Column('requiere_override', sa.Boolean(), nullable=False),
    sa.Column('justificacion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('aprobado_por', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('program_document_url', sa.String(length=500), nullable=True),
    sa.Column('has_learning_structure', sa.Boolean(), nullable=False),
    sa.Column('grading_scale', sa.String(length=100), nullable=True),
    sa.Column('passing_threshold', sa.Float(), nullable=True),
    sa.Column('base_score_type', sa.String(length=100), nullable=True),
    sa.Column('norma_terminologica', sa.String(length=120), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('grupos',
    sa.Column('assessment_id', sa.String(length=64), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupos_assessment_id'), 'grupos', ['assessment_id'], unique=False)
    op.create_table('registros_validacion',
    sa.Column('respuesta_ref', sa.String(length=120), nullable=False),
    sa.Column('criterio', sa.String(length=255), nullable=False),
    sa.Column('assessment_id', sa.String(length=64), nullable=True),
    sa.Column('rubrica_version_hash', sa.String(length=64), nullable=True),
    sa.Column('nivel_ia', sa.String(length=20), nullable=False),
    sa.Column('confianza_ia', sa.Float(), nullable=False),
    sa.Column('nivel_docente', sa.String(length=20), nullable=False),
    sa.Column('accion', sa.String(length=20), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('docente', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registros_validacion_assessment_id'), 'registros_validacion', ['assessment_id'], unique=False)
    op.create_table('rubrica_versiones',
    sa.Column('answer_key_id', sa.String(length=120), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('parent_hash', sa.String(length=64), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('resumen', sa.Text(), nullable=True),
    sa.Column('autor', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sesiones_en_vivo',
    sa.Column('assessment_id', sa.String(length=64), nullable=False),
    sa.Column('codigo', sa.String(length=12), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='lobby', nullable=False),
    sa.Column('pregunta_actual', sa.Integer(), nullable=False),
    sa.Column('n_preguntas', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesiones_en_vivo_assessment_id'), 'sesiones_en_vivo', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_sesiones_en_vivo_codigo'), 'sesiones_en_vivo', ['codigo'], unique=True)
    op.create_table('suscripciones',
    sa.Column('cuenta_id', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.String(length=30), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('fin_periodo', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gateway', sa.String(length=20), nullable=True),
    sa.Column('ref_externa', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suscripciones_cuenta_id'), 'suscripciones', ['cuenta_id'], unique=True)
    op.create_table('teachers',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), server_default='profesor', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teachers_email'), 'teachers', ['email'], unique=True)
    op.create_table('assessments',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assessment_document_url', sa.String(length=500), nullable=True),
    sa.Column('has_versions', sa.Boolean(), nullable=False),
    sa.Column('version_count', sa.Integer(), nullable=False),
    sa.Column('has_answer_key', sa.Boolean(), nullable=False),
    sa.Column('briefing_level', sa.String(length=50), nullable=False),
    sa.Column('n_questions', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('grading_scale', sa.String(length=50), nullable=False),
    sa.Column('passing_threshold', sa.Float(), nullable=True),
    sa.Column('modalidad', sa.String(length=20), server_default='escrita', nullable=False),
    sa.Column('bandas_moviles', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventos_pago',
    sa.Column('suscripcion_id', sa.UUID(), nullable=False),
    sa.Column('gateway', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('monto_clp', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['suscripcion_id'], ['suscripciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_pago_idempotency_key'), 'eventos_pago', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_eventos_pago_suscripcion_id'), 'eventos_pago', ['suscripcion_id'], unique=False)
    op.create_table('grupo_integrantes',
    sa.Column('grupo_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupo_integrantes_student_id'), 'grupo_integrantes', ['student_id'], unique=False)
    op.create_table('learning_outcomes',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('unidad', sa.String(length=150), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_outcomes_course_id'), 'learning_outcomes', ['course_id'], unique=False)
    op.create_table('participantes_vivo',
    sa.Column('sesion_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=80), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=True),
    sa.Column('token', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones_en_vivo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participantes_vivo_sesion_id'), 'participantes_vivo', ['sesion_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_table('students',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=100), nullable=False),
    sa.Column('apellido_materno', sa.String(length=100), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('sexo', sa.String(length=20), nullable=True),
    sa.Column('dependencia', sa.String(length=40), nullable=True),
    sa.Column('consiente_equidad', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_rut'), 'students', ['rut'], unique=False)
    op.create_table('answer_keys',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('version_coverage_ok', sa.Boolean(), nullable=False),
    sa.Column('annulled_items_count', sa.Integer(), nullable=False),
    sa.Column('invalid_weight_count', sa.Integer(), nullable=False),
    sa.Column('invalid_partial_rule_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    op.create_table('respuestas_vivo',
    sa.Column('sesion_id', sa.UUID(), nullable=False),
    sa.Column('participante_id', sa.UUID(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('respuesta', sa.String(length=10), nullable=False),
    sa.Column('correcta', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes_vivo.id'], ),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones_en_vivo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participante_id', 'question_number', name='uq_resp_vivo')
    )
    op.create_index(op.f('ix_respuestas_vivo_participante_id'), 'respuestas_vivo', ['participante_id'], unique=False)
    op.create_index(op.f('ix_respuestas_vivo_sesion_id'), 'respuestas_vivo', ['sesion_id'], unique=False)
    op.create_table('scans',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('student_identifier', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('detected_version', sa.String(length=10), nullable=True),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('ambiguity_count', sa.Integer(), nullable=False),
    sa.Column('unresolved_ambiguity_count', sa.Integer(), nullable=False),
    sa.Column('review_reasons_json', sa.JSON(), nullable=True),
    sa.Column('sheet_image_url', sa.String(length=500), nullable=True),
    sa.Column('raw_ocr_payload_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer_key_items',
    sa.Column('answer_key_id', sa.UUID(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('correct_answer', sa.String(length=10), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('is_annulled', sa.Boolean(), nullable=False),
    sa.Column('partial_credit_rule_json', sa.JSON(), nullable=True),
    sa.Column('question_type', sa.String(length=30), server_default='multiple_choice', nullable=False),
    sa.Column('learning_outcome_id', sa.String(length=100), nullable=True),
    sa.Column('bloom_level', sa.String(length=50), nullable=True),
    sa.Column('unidad', sa.String(length=100), nullable=True),
    sa.Column('enunciado', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['answer_key_id'], ['answer_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rubric_criteria',
    sa.Column('answer_key_item_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('descriptor', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('nivel_exigencia', sa.String(length=20), server_default='tolerante', nullable=False),
    sa.Column('penaliza_forma', sa.Boolean(), nullable=False),
    sa.Column('sinonimos_json', sa.JSON(), nullable=True),
    sa.Column('umbral_confianza', sa.Float(), nullable=False),
    sa.Column('politica_creativo', sa.String(length=20), nullable=False),
    sa.Column('fuera_de_alcance', sa.Text(), nullable=True),
    sa.Column('niveles_json', sa.JSON(), nullable=True),
    sa.Column('seccion', sa.String(length=120), nullable=True),
    sa.Column('ambito', sa.String(length=20), server_default='individual', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['answer_key_item_id'], ['answer_key_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rubric_anclas',
    sa.Column('rubric_criterion_id', sa.UUID(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('nivel', sa.String(length=20), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['rubric_criterion_id'], ['rubric_criteria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rubric_anclas')
    op.drop_table('rubric_criteria')
    op.drop_table('answer_key_items')
    op.drop_table('scans')
    op.drop_index(op.f('ix_respuestas_vivo_sesion_id'), table_name='respuestas_vivo')
    op.drop_index(op.f('ix_respuestas_vivo_participante_id'), table_name='respuestas_vivo')
    op.drop_table('respuestas_vivo')
    op.drop_table('answer_keys')
    op.drop_index(op.f('ix_students_rut'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_participantes_vivo_sesion_id'), table_name='participantes_vivo')
    op.drop_table('participantes_vivo')
    op.drop_index(op.f('ix_learning_outcomes_course_id'), table_name='learning_outcomes')
    op.drop_table('learning_outcomes')
    op.drop_index(op.f('ix_grupo_integrantes_student_id'), table_name='grupo_integrantes')
    op.drop_table('grupo_integrantes')
    op.drop_index(op.f('ix_eventos_pago_suscripcion_id'), table_name='eventos_pago')
    op.drop_index(op.f('ix_eventos_pago_idempotency_key'), table_name='eventos_pago')
    op.drop_table('eventos_pago')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_teachers_email'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_suscripciones_cuenta_id'), table_name='suscripciones')
    op.drop_table('suscripciones')
    op.drop_index(op.f('ix_sesiones_en_vivo_codigo'), table_name='sesiones_en_vivo')
    op.drop_index(op.f('ix_sesiones_en_vivo_assessment_id'), table_name='sesiones_en_vivo')
    op.drop_table('sesiones_en_vivo')
    op.drop_table('rubrica_versiones')
    op.drop_index(op.f('ix_registros_validacion_assessment_id'), table_name='registros_validacion')
    op.drop_table('registros_validacion')
    op.drop_index(op.f('ix_grupos_assessment_id'), table_name='grupos')
    op.drop_table('grupos')
    op.drop_table('courses')
    op.drop_table('ajustes_calibracion')
    # ### end Alembic commands ###
